[package]
name = "llama-diffusion-structured"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = []
hip = ["llama-diffusion-sys/hip"]
cuda = ["llama-diffusion-sys/cuda"]
native = ["llama-diffusion-sys/native"]

[dependencies]
image.workspace = true
llama-diffusion-sys.workspace = true
clap.workspace = true
rand.workspace = true
rand_chacha.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
